language: php

php:
  - 7.0
  - 7.1

cache:
  directories:
    - $HOME/.composer/cache
    
before_install:
  - composer self-update
  - composer --version
  # install PHPSTAN for PHP 7+
  - if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.6" ]]; then composer global require phpstan/phpstan-shim; fi
  
install:
  - composer install

script:
  # Check if the code standards weren't broken.
  # Run it only on PHP 7.1 which should be the fastest. No need to run it for all PHP versions
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.1" ]]; then bin/php-cs-fixer fix -v --dry-run --diff; fi
